version: "3.7"
services:
  app:
    build:
      args:
        user: debian
        uid: 1000
      context: ./docker-compose/php
      dockerfile: Dockerfile
    image: app
    container_name: app-php
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./htdocs:/var/www
    networks:
      - app

  db:
    image: mysql:8.0
    container_name: app-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app
    volumes:
      - ./db:/var/lib/mysql  

  nginx:
    image: nginx:alpine
    container_name: app-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./htdocs:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - app

  cache:
    image: redis:latest
    container_name: app-cache
    restart: always
    networks:
      - app

networks:
  app:
    driver: bridge
