name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: cd htdocs/core && php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: cd htdocs/core && composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: cd htdocs/core && php artisan key:generate
    - name: Directory Permissions
      run: cd htdocs/core && chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p htdocs/core/database
        touch htdocs/core/database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: htdocs/core/database/database.sqlite
      run: htdocs/core/vendor/bin/phpunit htdocs/core/tests/Unit
